### ISSUE TITLE
Gulp improvements

### ISSUE THREAD

**Issue by HonzaMikula** [salsita/generator-salsa-ui#1]
- On Windows from time to time happen that gulp crash.
- Gulp watch should not crash, when you have error in LESS. It should just show you error and play some sound (like grunt do).
- If you have error in LESS, gulp doesn't show you where the error is, so it's really difficult to locate the error in many cases.

**Comment by caryfuk** [comment]
Here is the solution to it: https://github.com/salsita/generator-salsa-ui/compare/master...caryfuk:patch-2 please merge.

**Comment by miky-btc** [comment]
Great!
